# Generated by Django 2.2.1 on 2019-05-24 09:34

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('photo', models.ImageField(upload_to='profile_photo/%Y/%m/%d', verbose_name='Фотография')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='email', unique_with=['city'], verbose_name='url')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='Город')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Профили пользователей',
                'verbose_name': 'Профиль пользователя',
            },
        ),
    ]
