# Generated by Django 2.1.9 on 2019-06-07 04:12

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=128, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='телефон')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='first_name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь системы')),
            ],
            options={
                'verbose_name_plural': 'Пользователи системы',
                'verbose_name': 'Пользователь системы',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=128, verbose_name='Юридическое наименование')),
                ('brand', models.CharField(max_length=128, verbose_name='Торговая марка')),
                ('logo', models.ImageField(upload_to='tenant/logo/%y/%m/%d', verbose_name='Логотип')),
                ('bin_code', models.IntegerField(verbose_name='БИН')),
                ('bank_props', models.CharField(choices=[('Каспи', 'Каспибанк'), ('Сбер', 'Сбербанк'), ('АТФ', 'АТФБанк'), ('ЕБ', 'Евразийский банк'), ('КН', 'Kassa Nova банк'), ('ВТБ', 'Банк ВТБ'), ('АК', 'AsiaCredit Bank'), ('ХК', 'ДБ Хоум Кредит энд Финанс Банк'), ('АБ', 'ДБ Альфа-Банк'), ('НБ', 'Нурбанк'), ('РБК', 'Bank RBK'), ('ФБ', 'ForteBank'), ('ЦК', 'Банк ЦентрКредит'), ('НБК', 'Народный Банк')], default='', max_length=7, verbose_name='Банк')),
                ('bank_bic', models.CharField(max_length=25, verbose_name='БИК')),
                ('checking_account', models.IntegerField(verbose_name='Расчетный счет')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='legal_name', unique_with=['brand'])),
            ],
            options={
                'verbose_name_plural': 'Тенанты',
                'verbose_name': 'Тенант',
            },
        ),
    ]
