# Generated by Django 2.2.2 on 2019-06-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='publish',
        ),
    ]
