# Generated by Django 2.2.2 on 2019-07-02 07:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_sale_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='product'),
        ),
    ]
