# Generated by Django 2.2.2 on 2019-07-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190702_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleimage',
            old_name='property',
            new_name='sale',
        ),
    ]
