# Generated by Django 2.2.1 on 2019-05-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
