# Generated by Django 2.2.2 on 2019-06-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190624_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post/%Y/%m', verbose_name='картинки'),
        ),
    ]
