# Generated by Django 2.2.2 on 2019-06-27 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190627_0344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
