# Generated by Django 2.2.2 on 2019-07-02 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_sale_saleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
