# Generated by Django 2.2.2 on 2019-07-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190702_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='image',
            field=models.ImageField(upload_to='sales/%Y/%m', verbose_name='фото'),
        ),
    ]
