# Generated by Django 2.2.1 on 2019-05-24 05:01

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_area', '0002_auto_20190524_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=11111, upload_to='post/%Y/%m/%d', verbose_name='Фотографии'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['author', 'published_date__month']),
        ),
    ]
