# Generated by Django 2.2.1 on 2019-05-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_area', '0003_auto_20190524_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='moderation',
            field=models.BooleanField(default=False, verbose_name='Модерация'),
        ),
    ]
