# Generated by Django 2.2.1 on 2019-05-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
