# Generated by Django 2.2.1 on 2019-05-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_auto_20190515_1041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
