# Generated by Django 2.2.2 on 2019-06-05 07:28

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Максимум 78 символов', max_length=78, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, help_text='Максимум 158 символа', max_length=158, verbose_name='Описание')),
                ('content', tinymce.models.HTMLField(verbose_name='Контент')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('timestamp',))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Список тегов через запятую', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги')),
            ],
        ),
    ]
