# Generated by Django 2.2.2 on 2019-06-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_area_posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
