# Generated by Django 2.2.2 on 2019-06-05 07:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_area_posts', '0002_remove_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('author',)),
        ),
    ]
