# Generated by Django 2.2.2 on 2019-06-05 06:19

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('print_area_members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=2, editable=False, populate_from='legal_name', unique_with=['brand']),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь системы')),
            ],
        ),
    ]
