# Generated by Django 2.2.2 on 2019-06-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_area_members', '0004_auto_20190605_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='телефон'),
        ),
    ]
