# Generated by Django 2.2.2 on 2019-06-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_area_members', '0005_auto_20190605_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemuser',
            options={'verbose_name': 'Пользователь системы', 'verbose_name_plural': 'Пользователи системы'},
        ),
        migrations.AddField(
            model_name='systemuser',
            name='first_name',
            field=models.CharField(default=1, max_length=128, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemuser',
            name='last_name',
            field=models.CharField(default=1, max_length=128, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
