# Generated by Django 2.2.2 on 2019-06-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_area_members', '0006_auto_20190605_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='patronymic',
            field=models.CharField(default=1, max_length=128, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Фамилия'),
        ),
    ]
