# Generated by Django 2.2.2 on 2019-06-26 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('comment', models.CharField(max_length=500, verbose_name='коментарии')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='коментарии к посту')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
